name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:10.8
        env:
          POSTGRES_USER: testadmin
          POSTGRES_PASSWORD: totallyrealpassword
          POSTGRES_DB: DjangoML
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7, 3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: psycopg2 prerequisites
      run: sudo apt-get install python-dev libpq-dev
    - name: Install Dependencies and build project
      run: |
        cd DjangoMLServer
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cp DjangoMLServer/.env.test DjangoMLServer/.env
        python manage.py migrate
    - name: Run Tests
      run: |
        cd DjangoMLServer
        python manage.py test
